"""add watchlist table

Revision ID: 14cee4d7db29
Revises: ab0606ae8cb5
Create Date: 2026-05-31 22:12:06.560998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14cee4d7db29'
down_revision: Union[str, Sequence[str], None] = 'ab0606ae8cb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_watchlist_user_movie', 'watchlists', ['user_id', 'movie_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_watchlist_user_movie', 'watchlists', type_='unique')
    # ### end Alembic commands ###
