from enum import StrEnum

class ErrorCode(StrEnum):
    EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    MOVIE_ALREADY_IN_WATCHLIST = "MOVIE_ALREADY_IN_WATCHLIST"